//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BizTbl_Culture
    {
        public BizTbl_Culture()
        {
            this.TB_Hotel = new HashSet<TB_Hotel>();
            this.TB_HotelHistory = new HashSet<TB_HotelHistory>();
            this.TB_Reservation = new HashSet<TB_Reservation>();
            this.TB_ReservationHistory = new HashSet<TB_ReservationHistory>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string SystemCode { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
        public virtual ICollection<TB_HotelHistory> TB_HotelHistory { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation { get; set; }
        public virtual ICollection<TB_ReservationHistory> TB_ReservationHistory { get; set; }
    }
}
