//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenPolicySummary
    {
        public int ID { get; set; }
        public bool HasChildrenPolicy { get; set; }
        public bool HasExtraBedPolicy { get; set; }
        public Nullable<int> MaxNoExtraBed { get; set; }
        public Nullable<int> MaxNoOfChild { get; set; }
        public Nullable<decimal> ChildrenPrice { get; set; }
        public Nullable<decimal> AdultPrice { get; set; }
        public Nullable<int> HotelID { get; set; }
    
        public virtual TB_Hotel TB_Hotel { get; set; }
    }
}
