//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenPoliciesHeader
    {
        public ChildrenPoliciesHeader()
        {
            this.ChildrenPolicyItems = new HashSet<ChildrenPolicyItem>();
            this.HotelChildrenPolicies = new HashSet<HotelChildrenPolicy>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
        public string Description_en { get; set; }
        public string Description_tr { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_ja { get; set; }
        public string Description_pt { get; set; }
        public string Description_zh { get; set; }
        public Nullable<short> Sort { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> OpDateTime { get; set; }
        public Nullable<long> OpUserID { get; set; }
        public Nullable<int> PolicyType { get; set; }
    
        public virtual ICollection<ChildrenPolicyItem> ChildrenPolicyItems { get; set; }
        public virtual ICollection<HotelChildrenPolicy> HotelChildrenPolicies { get; set; }
    }
}
