//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildrenPolicy
    {
        public long ID { get; set; }
        public bool IsAccommodate { get; set; }
        public bool IsExtraBedProvided { get; set; }
        public Nullable<int> NoOfExtraBed { get; set; }
        public Nullable<bool> IsTwoYearsChild { get; set; }
        public Nullable<decimal> TwoYearsChildCharge { get; set; }
        public Nullable<bool> IsExtraBedChild { get; set; }
        public Nullable<int> ExtraBedChildUnit { get; set; }
        public Nullable<bool> IsAdult { get; set; }
        public Nullable<decimal> AdultCharge { get; set; }
        public Nullable<bool> IsExistingBedChild { get; set; }
        public Nullable<int> ExistingBedChildUnit { get; set; }
        public Nullable<int> ExistingBedChildCount { get; set; }
        public Nullable<decimal> ExistingBedChildCharge { get; set; }
        public int HotelID { get; set; }
        public int CurrencyID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
    }
}
