//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelChildrenPolicy
    {
        public int ID { get; set; }
        public int ChildrenPolicyHeaderID { get; set; }
        public int ChildrenPolicyItemID { get; set; }
        public int HotelID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NoOfExtraBed { get; set; }
        public Nullable<int> NoOfChildExistingBed { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public int ChildUnitID { get; set; }
        public Nullable<bool> IsAttributeSelected { get; set; }
        public Nullable<bool> IsChildrenAccommodated { get; set; }
        public Nullable<bool> IsExtrabedNeeded { get; set; }
    
        public virtual ChildrenPoliciesHeader ChildrenPoliciesHeader { get; set; }
        public virtual ChildrenPolicyItem ChildrenPolicyItem { get; set; }
        public virtual ChildrenPolicyUnit ChildrenPolicyUnit { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
    }
}
