//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPropertyPolicy
    {
        public int ID { get; set; }
        public int PropertyPolicyID { get; set; }
        public int PropertyPolicyItemID { get; set; }
        public int HotelID { get; set; }
        public int UnitID { get; set; }
        public string UnitValue { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CurrencyID { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual PropertyPolicy PropertyPolicy { get; set; }
        public virtual PropertyPolicyUnit PropertyPolicyUnit { get; set; }
        public virtual PropertyPolicyItem PropertyPolicyItem { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
    }
}
