//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelCancellationPolicy
    {
        public int ID { get; set; }
        public int HotellD { get; set; }
        public Nullable<bool> IsPublicDisplay { get; set; }
        public Nullable<bool> IsPrivateDisplay { get; set; }
        public Nullable<bool> IsPromotionDisplay { get; set; }
        public Nullable<bool> IsPeriodExists { get; set; }
        public Nullable<int> ArrivalTypeID { get; set; }
        public Nullable<int> ArrivalRateID { get; set; }
        public Nullable<int> PrepaymentTypeID { get; set; }
        public Nullable<int> CancelRateID { get; set; }
        public Nullable<bool> IsPrepayment { get; set; }
    
        public virtual HotelCancellationPolicy HotelCancellationPolicy1 { get; set; }
        public virtual HotelCancellationPolicy HotelCancellationPolicy2 { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
        public virtual TB_TypePenaltyRate TB_TypePenaltyRate { get; set; }
        public virtual TB_TypePenaltyRate TB_TypePenaltyRate1 { get; set; }
        public virtual TB_TypePenaltyRate TB_TypePenaltyRate2 { get; set; }
        public virtual TB_TypePrepayment TB_TypePrepayment { get; set; }
    }
}
