//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPolicySummary
    {
        public int ID { get; set; }
        public int HotelID { get; set; }
        public string Description { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Icons { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
    }
}
