//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyPolicyItem
    {
        public PropertyPolicyItem()
        {
            this.HotelPropertyPolicies = new HashSet<HotelPropertyPolicy>();
            this.PropertyPolicyUnits = new HashSet<PropertyPolicyUnit>();
            this.PropertyPolicyItems1 = new HashSet<PropertyPolicyItem>();
        }
    
        public int ID { get; set; }
        public int PropertyPolicyID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsParentItem { get; set; }
        public Nullable<bool> IsChargedItem { get; set; }
        public string PriceLabel { get; set; }
        public Nullable<int> ParentPolicyItemID { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string RelatedIcon { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<HotelPropertyPolicy> HotelPropertyPolicies { get; set; }
        public virtual PropertyPolicy PropertyPolicy { get; set; }
        public virtual ICollection<PropertyPolicyUnit> PropertyPolicyUnits { get; set; }
        public virtual ICollection<PropertyPolicyItem> PropertyPolicyItems1 { get; set; }
        public virtual PropertyPolicyItem PropertyPolicyItem1 { get; set; }
    }
}
