//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Currency
    {
        public TB_Currency()
        {
            this.ChildrenPolicies = new HashSet<ChildrenPolicy>();
            this.HotelChildrenPolicies = new HashSet<HotelChildrenPolicy>();
            this.HotelPropertyPolicies = new HashSet<HotelPropertyPolicy>();
            this.TB_Bank = new HashSet<TB_Bank>();
            this.TB_BankHistory = new HashSet<TB_BankHistory>();
            this.TB_BusinessPartner = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner1 = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner2 = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner3 = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner4 = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartner5 = new HashSet<TB_BusinessPartner>();
            this.TB_BusinessPartnerHistory = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_BusinessPartnerHistory1 = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_BusinessPartnerHistory2 = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_BusinessPartnerHistory3 = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_BusinessPartnerHistory4 = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_BusinessPartnerHistory5 = new HashSet<TB_BusinessPartnerHistory>();
            this.TB_Country = new HashSet<TB_Country>();
            this.TB_Deal = new HashSet<TB_Deal>();
            this.TB_Deal1 = new HashSet<TB_Deal>();
            this.TB_Deal2 = new HashSet<TB_Deal>();
            this.TB_DealHistory = new HashSet<TB_DealHistory>();
            this.TB_DealReservation = new HashSet<TB_DealReservation>();
            this.TB_DealReservation1 = new HashSet<TB_DealReservation>();
            this.TB_DealReservation2 = new HashSet<TB_DealReservation>();
            this.TB_DealReservation3 = new HashSet<TB_DealReservation>();
            this.TB_DealReservation4 = new HashSet<TB_DealReservation>();
            this.TB_DealReservationHistory = new HashSet<TB_DealReservationHistory>();
            this.TB_DealReservationHistory1 = new HashSet<TB_DealReservationHistory>();
            this.TB_DealReservationHistory2 = new HashSet<TB_DealReservationHistory>();
            this.TB_DealReservationHistory3 = new HashSet<TB_DealReservationHistory>();
            this.TB_DealReservationHistory4 = new HashSet<TB_DealReservationHistory>();
            this.TB_ExchangeRate = new HashSet<TB_ExchangeRate>();
            this.TB_ExchangeRateHistory = new HashSet<TB_ExchangeRateHistory>();
            this.TB_Hotel = new HashSet<TB_Hotel>();
            this.TB_HotelAttribute = new HashSet<TB_HotelAttribute>();
            this.TB_HotelAttributeHistory = new HashSet<TB_HotelAttributeHistory>();
            this.TB_HotelHistory = new HashSet<TB_HotelHistory>();
            this.TB_HotelRate = new HashSet<TB_HotelRate>();
            this.TB_HotelRate1 = new HashSet<TB_HotelRate>();
            this.TB_HotelRateHistory = new HashSet<TB_HotelRateHistory>();
            this.TB_HotelReservation = new HashSet<TB_HotelReservation>();
            this.TB_HotelReservationHistory = new HashSet<TB_HotelReservationHistory>();
            this.TB_HotelRate2 = new HashSet<TB_HotelRate>();
            this.TB_HotelReservationRate = new HashSet<TB_HotelReservationRate>();
            this.TB_HotelReservationRateHistory = new HashSet<TB_HotelReservationRateHistory>();
            this.TB_Invoice = new HashSet<TB_Invoice>();
            this.TB_InvoiceHistory = new HashSet<TB_InvoiceHistory>();
            this.TB_Reservation = new HashSet<TB_Reservation>();
            this.TB_Reservation1 = new HashSet<TB_Reservation>();
            this.TB_Reservation2 = new HashSet<TB_Reservation>();
            this.TB_Reservation3 = new HashSet<TB_Reservation>();
            this.TB_ReservationHistory = new HashSet<TB_ReservationHistory>();
            this.TB_ReservationHistory1 = new HashSet<TB_ReservationHistory>();
            this.TB_ReservationHistory2 = new HashSet<TB_ReservationHistory>();
            this.TB_ReservationHistory3 = new HashSet<TB_ReservationHistory>();
            this.TB_Tour = new HashSet<TB_Tour>();
            this.TB_Tour1 = new HashSet<TB_Tour>();
            this.TB_Tour2 = new HashSet<TB_Tour>();
            this.TB_TourHistory = new HashSet<TB_TourHistory>();
            this.TB_TourHistory1 = new HashSet<TB_TourHistory>();
            this.TB_TourReservation = new HashSet<TB_TourReservation>();
            this.TB_TourReservation1 = new HashSet<TB_TourReservation>();
            this.TB_TourReservation2 = new HashSet<TB_TourReservation>();
            this.TB_TourReservation3 = new HashSet<TB_TourReservation>();
            this.TB_TourReservation4 = new HashSet<TB_TourReservation>();
            this.TB_TourReservationHistory = new HashSet<TB_TourReservationHistory>();
            this.TB_TourReservationHistory1 = new HashSet<TB_TourReservationHistory>();
            this.TB_TourReservationHistory2 = new HashSet<TB_TourReservationHistory>();
            this.TB_TourReservationHistory3 = new HashSet<TB_TourReservationHistory>();
            this.TB_TourReservationHistory4 = new HashSet<TB_TourReservationHistory>();
            this.TB_Transfer = new HashSet<TB_Transfer>();
            this.TB_Transfer1 = new HashSet<TB_Transfer>();
            this.TB_Transfer2 = new HashSet<TB_Transfer>();
            this.TB_TransferHistory = new HashSet<TB_TransferHistory>();
            this.TB_TransferHistory1 = new HashSet<TB_TransferHistory>();
            this.TB_TransferHistory2 = new HashSet<TB_TransferHistory>();
            this.TB_TransferReservation = new HashSet<TB_TransferReservation>();
            this.TB_TransferReservation1 = new HashSet<TB_TransferReservation>();
            this.TB_TransferReservation2 = new HashSet<TB_TransferReservation>();
            this.TB_TransferReservation3 = new HashSet<TB_TransferReservation>();
            this.TB_TransferReservation4 = new HashSet<TB_TransferReservation>();
            this.TB_TransferReservationHistory = new HashSet<TB_TransferReservationHistory>();
            this.TB_TransferReservationHistory1 = new HashSet<TB_TransferReservationHistory>();
            this.TB_TypeHotelBudget = new HashSet<TB_TypeHotelBudget>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Symbol { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_pt { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public string Name_zh { get; set; }
        public Nullable<short> Sort { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual ICollection<ChildrenPolicy> ChildrenPolicies { get; set; }
        public virtual ICollection<HotelChildrenPolicy> HotelChildrenPolicies { get; set; }
        public virtual ICollection<HotelPropertyPolicy> HotelPropertyPolicies { get; set; }
        public virtual ICollection<TB_Bank> TB_Bank { get; set; }
        public virtual ICollection<TB_BankHistory> TB_BankHistory { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner1 { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner2 { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner3 { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner4 { get; set; }
        public virtual ICollection<TB_BusinessPartner> TB_BusinessPartner5 { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory1 { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory2 { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory3 { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory4 { get; set; }
        public virtual ICollection<TB_BusinessPartnerHistory> TB_BusinessPartnerHistory5 { get; set; }
        public virtual ICollection<TB_Country> TB_Country { get; set; }
        public virtual ICollection<TB_Deal> TB_Deal { get; set; }
        public virtual ICollection<TB_Deal> TB_Deal1 { get; set; }
        public virtual ICollection<TB_Deal> TB_Deal2 { get; set; }
        public virtual ICollection<TB_DealHistory> TB_DealHistory { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation1 { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation2 { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation3 { get; set; }
        public virtual ICollection<TB_DealReservation> TB_DealReservation4 { get; set; }
        public virtual ICollection<TB_DealReservationHistory> TB_DealReservationHistory { get; set; }
        public virtual ICollection<TB_DealReservationHistory> TB_DealReservationHistory1 { get; set; }
        public virtual ICollection<TB_DealReservationHistory> TB_DealReservationHistory2 { get; set; }
        public virtual ICollection<TB_DealReservationHistory> TB_DealReservationHistory3 { get; set; }
        public virtual ICollection<TB_DealReservationHistory> TB_DealReservationHistory4 { get; set; }
        public virtual ICollection<TB_ExchangeRate> TB_ExchangeRate { get; set; }
        public virtual ICollection<TB_ExchangeRateHistory> TB_ExchangeRateHistory { get; set; }
        public virtual ICollection<TB_Hotel> TB_Hotel { get; set; }
        public virtual ICollection<TB_HotelAttribute> TB_HotelAttribute { get; set; }
        public virtual ICollection<TB_HotelAttributeHistory> TB_HotelAttributeHistory { get; set; }
        public virtual ICollection<TB_HotelHistory> TB_HotelHistory { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate1 { get; set; }
        public virtual ICollection<TB_HotelRateHistory> TB_HotelRateHistory { get; set; }
        public virtual ICollection<TB_HotelReservation> TB_HotelReservation { get; set; }
        public virtual ICollection<TB_HotelReservationHistory> TB_HotelReservationHistory { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate2 { get; set; }
        public virtual ICollection<TB_HotelReservationRate> TB_HotelReservationRate { get; set; }
        public virtual ICollection<TB_HotelReservationRateHistory> TB_HotelReservationRateHistory { get; set; }
        public virtual ICollection<TB_Invoice> TB_Invoice { get; set; }
        public virtual ICollection<TB_InvoiceHistory> TB_InvoiceHistory { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation1 { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation2 { get; set; }
        public virtual ICollection<TB_Reservation> TB_Reservation3 { get; set; }
        public virtual ICollection<TB_ReservationHistory> TB_ReservationHistory { get; set; }
        public virtual ICollection<TB_ReservationHistory> TB_ReservationHistory1 { get; set; }
        public virtual ICollection<TB_ReservationHistory> TB_ReservationHistory2 { get; set; }
        public virtual ICollection<TB_ReservationHistory> TB_ReservationHistory3 { get; set; }
        public virtual ICollection<TB_Tour> TB_Tour { get; set; }
        public virtual ICollection<TB_Tour> TB_Tour1 { get; set; }
        public virtual ICollection<TB_Tour> TB_Tour2 { get; set; }
        public virtual ICollection<TB_TourHistory> TB_TourHistory { get; set; }
        public virtual ICollection<TB_TourHistory> TB_TourHistory1 { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation1 { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation2 { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation3 { get; set; }
        public virtual ICollection<TB_TourReservation> TB_TourReservation4 { get; set; }
        public virtual ICollection<TB_TourReservationHistory> TB_TourReservationHistory { get; set; }
        public virtual ICollection<TB_TourReservationHistory> TB_TourReservationHistory1 { get; set; }
        public virtual ICollection<TB_TourReservationHistory> TB_TourReservationHistory2 { get; set; }
        public virtual ICollection<TB_TourReservationHistory> TB_TourReservationHistory3 { get; set; }
        public virtual ICollection<TB_TourReservationHistory> TB_TourReservationHistory4 { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer1 { get; set; }
        public virtual ICollection<TB_Transfer> TB_Transfer2 { get; set; }
        public virtual ICollection<TB_TransferHistory> TB_TransferHistory { get; set; }
        public virtual ICollection<TB_TransferHistory> TB_TransferHistory1 { get; set; }
        public virtual ICollection<TB_TransferHistory> TB_TransferHistory2 { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation1 { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation2 { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation3 { get; set; }
        public virtual ICollection<TB_TransferReservation> TB_TransferReservation4 { get; set; }
        public virtual ICollection<TB_TransferReservationHistory> TB_TransferReservationHistory { get; set; }
        public virtual ICollection<TB_TransferReservationHistory> TB_TransferReservationHistory1 { get; set; }
        public virtual ICollection<TB_TypeHotelBudget> TB_TypeHotelBudget { get; set; }
    }
}
