//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Continents
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Continents_tr { get; set; }
        public string Continents_en { get; set; }
        public string Continents_de { get; set; }
        public string Continents_es { get; set; }
        public string Continents_fr { get; set; }
        public string Continents_ru { get; set; }
        public string Continents_it { get; set; }
        public string Continents_ar { get; set; }
        public string Continents_pt { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
