//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Date
    {
        public TB_Date()
        {
            this.TB_ExchangeRate = new HashSet<TB_ExchangeRate>();
            this.TB_ExchangeRateHistory = new HashSet<TB_ExchangeRateHistory>();
            this.TB_HotelAvailabilityHistory = new HashSet<TB_HotelAvailabilityHistory>();
            this.TB_HotelAvailability = new HashSet<TB_HotelAvailability>();
            this.TB_HotelRate = new HashSet<TB_HotelRate>();
            this.TB_HotelRate1 = new HashSet<TB_HotelRate>();
            this.TB_HotelRateHistory = new HashSet<TB_HotelRateHistory>();
            this.TB_HotelRate2 = new HashSet<TB_HotelRate>();
            this.TB_HotelReservationRate = new HashSet<TB_HotelReservationRate>();
            this.TB_HotelReservationRateHistory = new HashSet<TB_HotelReservationRateHistory>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<TB_ExchangeRate> TB_ExchangeRate { get; set; }
        public virtual ICollection<TB_ExchangeRateHistory> TB_ExchangeRateHistory { get; set; }
        public virtual ICollection<TB_HotelAvailabilityHistory> TB_HotelAvailabilityHistory { get; set; }
        public virtual ICollection<TB_HotelAvailability> TB_HotelAvailability { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate1 { get; set; }
        public virtual ICollection<TB_HotelRateHistory> TB_HotelRateHistory { get; set; }
        public virtual ICollection<TB_HotelRate> TB_HotelRate2 { get; set; }
        public virtual ICollection<TB_HotelReservationRate> TB_HotelReservationRate { get; set; }
        public virtual ICollection<TB_HotelReservationRateHistory> TB_HotelReservationRateHistory { get; set; }
    }
}
