//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelReservationHistory
    {
        public long ID { get; set; }
        public long HotelReservationID { get; set; }
        public long ReservationID { get; set; }
        public int HotelID { get; set; }
        public int HotelRoomID { get; set; }
        public Nullable<int> HotelAccommodationTypeID { get; set; }
        public string GuestFullName { get; set; }
        public Nullable<int> PeopleCount { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public short NightCount { get; set; }
        public Nullable<int> HotelCancelPolicyID { get; set; }
        public Nullable<int> PricePolicyTypeID { get; set; }
        public Nullable<bool> NonRefundable { get; set; }
        public Nullable<bool> SingleRate { get; set; }
        public Nullable<bool> DoubleRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PromotionDiscountPercentage { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> BedOptionNo { get; set; }
        public string EstimatedArrivalTime { get; set; }
        public Nullable<int> TravellerTypeID { get; set; }
        public Nullable<System.DateTime> CancelDateTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ReservationOperationID { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public long LogUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Currency TB_Currency { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
        public virtual TB_HotelCancelPolicy TB_HotelCancelPolicy { get; set; }
        public virtual TB_HotelRoom TB_HotelRoom { get; set; }
        public virtual TB_Reservation TB_Reservation { get; set; }
        public virtual TB_TypeHotelAccommodation TB_TypeHotelAccommodation { get; set; }
        public virtual TB_TypePricePolicy TB_TypePricePolicy { get; set; }
        public virtual TB_TypeReservationOperation TB_TypeReservationOperation { get; set; }
        public virtual TB_TypeReservationStatus TB_TypeReservationStatus { get; set; }
        public virtual TB_TypeTraveller TB_TypeTraveller { get; set; }
    }
}
