//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelRoomHistory
    {
        public int ID { get; set; }
        public int HotelRoomID { get; set; }
        public int HotelID { get; set; }
        public string Description_tr { get; set; }
        public string Description_en { get; set; }
        public string Description_de { get; set; }
        public string Description_es { get; set; }
        public string Description_fr { get; set; }
        public string Description_ru { get; set; }
        public string Description_it { get; set; }
        public string Description_ar { get; set; }
        public string Description_jp { get; set; }
        public int RoomTypeID { get; set; }
        public int RoomCount { get; set; }
        public int RoomSize { get; set; }
        public short MaxPeopleCount { get; set; }
        public Nullable<short> MaxChildrenCount { get; set; }
        public short BabyCotCount { get; set; }
        public short ExtraBedCount { get; set; }
        public Nullable<int> SmokingTypeID { get; set; }
        public Nullable<int> ViewTypeID { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public long CreateUserID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public long LogUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
        public virtual TB_TypeRoom TB_TypeRoom { get; set; }
        public virtual TB_TypeSmoking TB_TypeSmoking { get; set; }
        public virtual TB_TypeView TB_TypeView { get; set; }
    }
}
