//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelSearchParameter
    {
        public TB_HotelSearchParameter()
        {
            this.TB_HotelSearch = new HashSet<TB_HotelSearch>();
        }
    
        public long ID { get; set; }
        public string Culture { get; set; }
        public Nullable<int> UserCountryID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string RegionIDs { get; set; }
        public string RegionNames { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> RoomCount { get; set; }
        public string GuestCount { get; set; }
        public Nullable<decimal> LowerUSDPrice { get; set; }
        public Nullable<decimal> UpperUSDPrice { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TB_Country TB_Country { get; set; }
        public virtual TB_Country TB_Country1 { get; set; }
        public virtual ICollection<TB_HotelSearch> TB_HotelSearch { get; set; }
        public virtual TB_Region TB_Region { get; set; }
    }
}
