//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HotelCancelPolicyHistory
    {
        public long ID { get; set; }
        public int HotelCancelPolicyID { get; set; }
        public int HotelID { get; set; }
        public int CancelTypeID { get; set; }
        public Nullable<int> RefundableDayCount { get; set; }
        public Nullable<int> PenaltyRateTypeID { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> OpDateTime { get; set; }
        public Nullable<long> OpUserID { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public Nullable<long> LogUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual BizTbl_User BizTbl_User1 { get; set; }
        public virtual TB_Hotel TB_Hotel { get; set; }
        public virtual TB_HotelCancelPolicyHistory TB_HotelCancelPolicyHistory1 { get; set; }
        public virtual TB_HotelCancelPolicyHistory TB_HotelCancelPolicyHistory2 { get; set; }
        public virtual TB_TypeCancel TB_TypeCancel { get; set; }
        public virtual TB_TypePenaltyRate TB_TypePenaltyRate { get; set; }
    }
}
