//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Messenger
    {
        public int ID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Message { get; set; }
        public System.DateTime Sent { get; set; }
        public int Recd { get; set; }
    }
}
