//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ReservationReviewDetail
    {
        public long ID { get; set; }
        public Nullable<long> ReservationReviewID { get; set; }
        public int ReviewTypeID { get; set; }
        public int ReviewScaleTypeID { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_ReservationReview TB_ReservationReview { get; set; }
        public virtual TB_TypeReview TB_TypeReview { get; set; }
        public virtual TB_TypeReviewScale TB_TypeReviewScale { get; set; }
    }
}
