//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TransferReservationPromotion
    {
        public int ID { get; set; }
        public long ReservationID { get; set; }
        public long TransferReservationID { get; set; }
        public int PromotionID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Promotion TB_Promotion { get; set; }
        public virtual TB_Reservation TB_Reservation { get; set; }
        public virtual TB_TransferReservation TB_TransferReservation { get; set; }
    }
}
