//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBSExtranet.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TypeReview
    {
        public TB_TypeReview()
        {
            this.TB_ReservationReviewDetail = new HashSet<TB_ReservationReviewDetail>();
            this.TB_ReservationReviewDetailHistory = new HashSet<TB_ReservationReviewDetailHistory>();
        }
    
        public int ID { get; set; }
        public int PartID { get; set; }
        public string Name_tr { get; set; }
        public string Name_en { get; set; }
        public string Name_de { get; set; }
        public string Name_es { get; set; }
        public string Name_fr { get; set; }
        public string Name_ru { get; set; }
        public string Name_it { get; set; }
        public string Name_ar { get; set; }
        public string Name_ja { get; set; }
        public Nullable<short> Sort { get; set; }
        public bool Active { get; set; }
        public System.DateTime OpDateTime { get; set; }
        public long OpUserID { get; set; }
        public string Name_pt { get; set; }
        public string Name_zh { get; set; }
    
        public virtual BizTbl_User BizTbl_User { get; set; }
        public virtual TB_Part TB_Part { get; set; }
        public virtual ICollection<TB_ReservationReviewDetail> TB_ReservationReviewDetail { get; set; }
        public virtual ICollection<TB_ReservationReviewDetailHistory> TB_ReservationReviewDetailHistory { get; set; }
    }
}
